### ISSUE TITLE
[Backend] REST API TEST

### ISSUE THREAD

**Issue by leezer94** [leezer94/fullstack_app#4]
## REST API TEST

---
#### /auth/signup
- [x] should throw an error with status code 400 if email is empty
- [x] should throw an error with status code 400 if password is empty
- [x] should throw an error with status code 400 if body is not given
- [x] should sign up

#### /auth/signin
- [x] should throw an error with status code 401 if email is empty
- [x] should throw an error with status code 400 if password is empty
- [x] should throw an error with status code 400 if body is not given
- [x] should sign in

#### /auth/logout
- [x] should delete hashed refresh token
- [x] should throw an error with status 401 if access token is not given

#### Refresh token
- [x] should throw an error with status code 401 when refresh token is not given
- [x] should update access token and refresh token
---
#### /todos
- [x] should return empty todos
- [x] should create new todo

#### /todos/id PATCH
- [x] should update todo by id
- [x] should throw an error with status code 401 when access_token is not given
- [x] should throw an error with status code 402 when status is not given

#### /todos/id DELETE
- [x] should delete todo by id

#### /todos DELETE
- [x] should delete all todos of user
